import 'package:flutter/material.dart';

class DataHelper {
  final List<String> sehirler = [
    "adana",
    "adiyaman",
    "afyonkarahisar",
    "agri",
    "aksaray",
    "amasya",
    "ankara",
    "antalya",
    "ardahan",
    "artvin",
    "aydin",
    "balikesir",
    "bartin",
    "batman",
    "bayburt",
    "bilecik",
    "bingol",
    "bitlis",
    "bolu",
    "burdur",
    "bursa",
    "canakkale",
    "cankiri",
    "corum",
    "denizli",
    "diyarbakir",
    "duzce",
    "edirne",
    "elazig",
    "erzincan",
    "erzurum",
    "eskisehir",
    "gaziantep",
    "giresun",
    "gumushane",
    "hakkari",
    "hatay",
    "igdir",
    "isparta",
    "istanbul",
    "izmir",
    "kahramanmaras",
    "karabuk",
    "karaman",
    "kars",
    "kastamonu",
    "kayseri",
    "kilis",
    "kirikkale",
    "kirklareli",
    "kirsehir",
    "kocaeli",
    "konya",
    "kutahya",
    "malatya",
    "manisa",
    "mardin",
    "mersin",
    "mugla",
    "mus",
    "nevsehir",
    "nigde",
    "ordu",
    "osmaniye",
    "rize",
    "sakarya",
    "samsun",
    "sanliurfa",
    "siirt",
    "sinop",
    "sivas",
    "sirnak",
    "tekirdag",
    "tokat",
    "trabzon",
    "tunceli",
    "usak",
    "van",
    "yalova",
    "yozgat",
    "zonguldak"
  ];

  final BoxDecoration AppBackgroundColorsDecoration = BoxDecoration(
    gradient: LinearGradient(
      colors: [
        Color.fromRGBO(7, 7, 35, 1),
        Color.fromRGBO(7, 15, 63, 1),
        Color.fromRGBO(9, 54, 97, 1),
      ],
      stops: [0.5, 0.8, 1],
      begin: Alignment.bottomLeft,
      end: Alignment.topRight,
    ),
  );
}
